name: Liquibase → BigQuery (PoC)

on:
  workflow_dispatch:
  push:
    paths:
      - 'liquibase/**'
      - '.github/workflows/bq-liquibase.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "BQ_DATASET=${{ secrets.BQ_DATASET }}" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Liquibase CLI
        run: |
          curl -L -o liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.zip
          unzip -q liquibase.zip -d $HOME/liquibase

      - name: Fetch Liquibase BigQuery extension (JAR)
        run: |
          mkdir -p lib
          curl -L -o lib/liquibase-bigquery.jar https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-bigquery/4.33.0/liquibase-bigquery-4.33.0.jar

        - name: Download BigQuery JDBC driver (Simba)
          run: |
            # Grab the current JDBC 4.2 driver zip from Google
            curl -L -o $RUNNER_TEMP/bqjdbc.zip "https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.6.3.1004.zip"
            unzip -q $RUNNER_TEMP/bqjdbc.zip -d $RUNNER_TEMP/bqjdbc
            mkdir -p lib
            # Copy the main jar and all dependencies from the zip into ./lib
            cp -v $RUNNER_TEMP/bqjdbc/GoogleBigQueryJDBC42.jar lib/ || true
            cp -v $RUNNER_TEMP/bqjdbc/*.jar lib/ || true
            cp -v $RUNNER_TEMP/bqjdbc/lib/*.jar lib/ || true
            ls -l lib

      - name: Write SA key to file & set ADC env
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $RUNNER_TEMP/sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json" >> $GITHUB_ENV

     - name: Liquibase update (apply DDL)
        env:
            LB: ${{ env.LB }}
            SA_KEY_PATH: ${{ env.SA_KEY_PATH }}
            PROJECT_ID: ${{ env.PROJECT_ID }}
            BQ_DATASET: ${{ env.BQ_DATASET }}
            SA_EMAIL: ${{ env.SA_EMAIL }}
        run: |
            CLASSPATH="lib/*"
            "$LB" \
              --driver=com.simba.googlebigquery.jdbc.Driver \
              --classpath="$CLASSPATH" \
              --url="jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=${PROJECT_ID};DefaultDataset=${BQ_DATASET};OAuthType=0;OAuthServiceAcctEmail=${SA_EMAIL};OAuthPvtKeyPath=${SA_KEY_PATH}" \
              --changeLogFile=liquibase/changelog.xml \
              --log-level=info \
              update 
